modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="tinkers_advanced"
version="${mod_version}"
displayName="Tinkers' Advanced"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile = "tiac_2.png"
[[dependencies.tinkers_advanced]]
    modId="forge"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_advanced]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_advanced]]
modId="etstlib"
mandatory=true
versionRange="[3.0.0-beta.10,)"
ordering="NONE"
side="BOTH"
[[dependencies.tinkers_advanced]]
modId="tconstruct"
mandatory=true
versionRange="[3.10.1.76,)"
ordering="AFTER"
side="BOTH"
